#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - git
  - tar
  - unzip
runcmd:
  - |
    echo "[1/5] Install k3s"
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig-mode 644" sh -
  - |
    echo "[2/5] Setup kubeconfig for common users"
    for U in ubuntu opc oracle; do
      if id "$U" >/dev/null 2>&1; then
        mkdir -p /home/$U/.kube
        cp /etc/rancher/k3s/k3s.yaml /home/$U/.kube/config
        chown -R $U:$U /home/$U/.kube
        chmod 600 /home/$U/.kube/config
      fi
    done
  - |
    echo "[3/5] Wait for node ready"
    until kubectl get nodes --no-headers 2>/dev/null | grep -q " Ready "; do sleep 5; done
  - |
    echo "[4/5] Install Ingress-NGINX (baremetal)"
    kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/baremetal/deploy.yaml
  - |
    echo "[5/5] Open firewall ports if firewalld exists"
    if command -v firewall-cmd >/dev/null 2>&1; then
      firewall-cmd --permanent --add-service=http || true
      firewall-cmd --permanent --add-service=https || true
      firewall-cmd --permanent --add-port=22/tcp || true
      firewall-cmd --reload || true
    fi
